/** Stable importable surface for the ArkGate architecture product. */
export { version } from './version';

export {
  ADAPTER_DIAGNOSTIC_DOCS_RELATIVE_PATH,
  ARK_ANALYSIS_RESULT_SCHEMA_VERSION,
  ARK_ANALYSIS_RESULT_SCHEMA,
  adapterDocsCodePath,
  adapterFindingOccurrenceTargetKeys,
  adapterFindingRefFromTargetKey,
  adapterFindingTargetKey,
  createAdapterResult,
  toAdapterDiagnostic,
  type AnalysisCompleteness,
  type AnalysisMode,
  type AdapterCompletenessReason,
  type AdapterDiagnostic,
  type AdapterResult,
  type AdapterSeverity,
  type AdapterViolationInput,
} from './domain/adapterContract';

export {
  ARK_PROJECT_IDENTITY_SCHEMA_VERSION,
  ARK_PROJECT_IDENTITY_SCHEMA_URL,
  ARK_PROJECT_IDENTITY_SCHEMA,
  PROJECT_EXPECTATION_SCHEMA,
  PROJECT_BINDING_SCHEMA,
  createProjectId,
  createProjectIdentity,
  type ProjectIdentity,
  type ProjectExpectation,
  type ProjectBinding,
} from './domain/projectIdentity';

export {
  createAICodeGate,
  type AICodeGate,
  type AICodeGateResult,
  type AICodeGateViolation,
  type AICodeGateContext,
  type AICodeGateOptions,
  type AIGateExtension,
} from './kernel/ai-gate';

export {
  createArchitectureProfile,
  createArchitectureProfileFromArkConfig,
  createElevenLayerArkConfig,
  elevenLayerProfile,
  type ArchitectureLayer,
  type ArchitectureLayerConfig,
  type ArchitectureProfile,
  type ArchitectureRule,
  type ArkCheckConfig,
  type CreateArchitectureProfileFromArkConfigOptions,
  type CreateArchitectureProfileOptions,
  type CreateElevenLayerArkConfigOptions,
} from './kernel/layers';

export {
  loadContract,
  analyzeProject,
  analyzeResolvedProject,
  analyzeChange,
  preflightChange,
  preflightResolvedChange,
  analyzePolicyDelta,
  analyzeArchitectureConvergence,
  explainViolation,
  evaluateArchitectureGraph,
  collectAnalysisConfigWarnings,
  detectArchitectureCycles,
  collectForbiddenCapabilityUses,
  extractSemanticDependencies,
  type AnalysisContract,
  type ArchitectureChangeMap,
  type ArchitectureChangeMapContract,
  type ArchitectureChangeMapDependency,
  type ArchitectureChangeMapFile,
  type ArchitectureChangeOperation,
  type AnalyzeArchitectureConvergenceInput,
  type ArchitectureActualChange,
  type ArchitectureConvergenceClassification,
  type ArchitectureConvergenceFinding,
  type ArchitectureConvergenceResult,
  type ArchitectureDependency,
  type AnalyzeProjectInput,
  type AnalyzeResolvedProjectInput,
  type PreflightResolvedChangeInput,
  type AnalyzeChangeInput,
  type AnalysisResult,
  type PreparedChangeFile,
  type ChangePreflightResult,
  type AnalyzePolicyDeltaInput,
  type PolicyDeltaAnalysis,
  type ArchitectureEngineViolation,
  type ArchitectureEngineEdge,
  type EvaluateArchitectureGraphInput,
  type ArchitectureEngineResult,
  type CollectAnalysisConfigWarningsInput,
  type ForbiddenCapabilityUse,
  type SemanticDependency,
  type SemanticDependencyKind,
  type ResolvedAnalysisFile,
  type ResolvedAnalysisIr,
  type ResolvedAnalysisResult,
  type ResolvedChangePreflightResult,
  type ResolvedSafetyReport,
} from './kernel/analysis';

export {
  POLICY_DELTA_SCHEMA_VERSION,
  classifyArkPolicyDelta,
  policyDeltaAcknowledgementMatches,
  type PolicyDelta,
  type PolicyDeltaAcknowledgement,
  type PolicyDeltaClassification,
  type PolicyDeltaFinding,
} from './domain/policyDelta';

export {
  ANALYSIS_IR_SCHEMA_VERSION,
  RESOLVED_CANDIDATE_FACTS_SCHEMA,
  RESOLVED_CANDIDATE_FACTS_SCHEMA_VERSION,
  createResolvedCandidateFacts,
  deterministicHash,
  loadResolvedCandidateFacts,
  resolvedFactsEvidenceRequirementsHash,
  stableSerialize,
  type AnalysisFileInput,
  type AnalysisFileChange,
  type AnalysisCompilerOptions,
  type AnalysisFile,
  type AnalysisImportEdge,
  type AnalysisCapabilityUse,
  type AnalysisEvidence,
  type AnalysisViolation,
  type AnalysisIr,
  type ResolvedAmbientFact,
  type ResolvedArkRunCompositionRootHitFact,
  type ResolvedArkRunDeclarationFact,
  type ResolvedArkRunKernelCallFact,
  type ResolvedArkRunKernelCallKind,
  type ResolvedArkRunManagedNewFact,
  type ResolvedCandidateFacts,
  type ResolvedCandidateFactsInput,
  type ResolvedCapability,
  type ResolvedCapabilityFact,
  type ResolvedDependencyFact,
  type ResolvedDependencyKind,
  type ResolvedDependencyState,
  type ResolvedFactsCompleteness,
  type ResolvedFactsReason,
  type ResolvedFileFact,
  type ResolvedIntentReferenceFact,
  type ResolvedPublishFact,
  type ResolvedSafetyFact,
  type ResolvedSafetyKind,
} from './domain/analysis';

export {
  ARK_CONFIG_SCHEMA,
  ARK_CONFIG_SCHEMA_VERSION,
  loadArkConfigContract,
  parseArkConfigJson,
  type ArkConfig,
  type ArkConfigLoadResult,
} from './domain/configContract';

export {
  ARK_RULES_SCHEMA,
  ARK_RULES_SCHEMA_VERSION,
  ARK_RULE_SENSORS,
  buildEffectiveArkRules,
  emptyEffectiveArkRules,
  loadArkRulesContract,
  parseArkRulesJson,
  type ArkRulesFile,
  type EffectiveArkRules,
} from './domain/arkRulesContract';

export {
  EffectiveContractError,
  effectiveContractPolicyPayload,
  resolveEffectiveContract,
  type EffectiveContract,
  type EffectiveContractWarning,
} from './domain/effectiveContract';

export {
  buildArkRuleFileHints,
  collectEmptyAppliesToFindings,
  deriveArkRuleFileHints,
  evaluateArkRuleSensors,
  extractClassShapesFromSource,
  type ClassShapeFact,
  type ArkRuleSensorViolation,
} from './domain/arkRuleSensors';

export {
  ARKRUN_KERNEL_FACTORY_CALLEES,
  ARKRUN_KERNEL_INTERACTION_CALLEES,
  ARKRUN_TRANSPORT_BYPASS_SPECIFIERS,
  arkRunKernelCallKind,
  extractArkRunDeclarationsFromSource,
  extractArkRunImportedConstructorNamesFromSource,
  extractArkRunKernelCallsFromSource,
  extractArkRunManagedNewsFromSource,
  extractArkRunValueImportDependenciesFromSource,
  isArkRunKernelModuleSpecifier,
  isArkRunTransportBypassSpecifier,
} from './domain/arkRunFacts';

export {
  EXTRA_MERGE_TEETH_GOVERNED_FLOOR,
  MERGE_PLANES_DUAL_STAMP,
  classifyResolvedLayerCoverage,
  composeMergePlanesHonesty,
  demoteExtraPlaneTeethUnderClassificationFloor,
  extraMergeTeethAllowed,
  isArkOrderRuleId,
  isArkRunRuleId,
  isExtraPlaneFinding,
  normalizeExtraMergeTeethClassification,
  type ExtraMergeTeethClassification,
  type MergePlanesHonesty,
} from './domain/extraMergeTeeth';

export {
  ARK_RUN_DOCTOR_SCHEMA_VERSION,
  formatArkRunDoctorLines,
  projectStatusArkRun,
  summarizeArkRunSection,
  type ArkRunDoctorSection,
  type ArkRunStatusSlice,
} from './domain/arkRunDoctor';

export {
  ARKRUN_INTERACTION_NAME_INCOMPLETE,
  ARKRUN_RULE_IDS,
  ARKRUN_TIER1_SENSOR_IDS,
  evaluateArkRunEditorSensors,
  evaluateArkRunEditorSensorsFromSource,
  evaluateArkRunSensors,
  type ArkRunRuleId,
  type ArkRunSensorFinding,
  type ArkRunTier1SensorId,
  type EvaluateArkRunSensorsInput,
  type EvaluateArkRunSensorsResult,
} from './domain/arkRunSensors';

export {
  ARKORDER_RULE_IDS,
  ARKORDER_TIER1_SENSOR_IDS,
  evaluateArkOrderSensors,
  type ArkOrderRuleId,
  type ArkOrderSensorFinding,
} from './domain/arkOrderSensors';

export {
  canPromoteInvariant,
  evaluateInvariantCoverage,
  type InvariantCoverageEvidence,
} from './domain/invariantCoverage';

export {
  buildRulesInventory,
  inventoryToExtractionCard,
  type RulesInventoryCandidate,
  type RulesInventoryResult,
} from './domain/rulesInventory';

export {
  ARK_ENFORCEMENT_STATE_SCHEMA_VERSION,
  type ArkEnforcementHost,
  type ArkEnforcementState,
  type EnforcementBoundaryState,
  type EnforcementEvidence,
  type EnforcementEvidenceField,
  type EnforcementVerification,
} from './domain/enforcementState';

export {
  ARK_DESIGN_DELTA_SCHEMA_VERSION,
  type ArkDesignDeltaResult,
  type DesignDeltaChange,
  type DesignDeltaEnforcementScope,
  type DesignDeltaIdentity,
  type DesignSmellEvidence,
  type DesignSmellFinding,
  type DesignSmellId,
} from './domain/designDelta';

export {
  DIAGNOSTIC_CATALOG,
  DIAGNOSTIC_CATALOG_SCHEMA_VERSION,
  DIAGNOSTIC_DOCS_RELATIVE_PATH,
  DIAGNOSTIC_RULE_IDS,
  catalogFixForRuleId,
  catalogWhyForRuleId,
  diagnosticDocsFragment,
  diagnosticDocsPath,
  getDiagnosticCatalogEntry,
  isCataloguedOrArkRuleFamily,
  isKnownDiagnosticCode,
  serializeDiagnosticCatalog,
  type DiagnosticCatalogEntry,
  type DiagnosticCategory,
} from './domain/diagnosticCatalog';

export {
  ARK_STATUS_MANIFEST_SCHEMA,
  ARK_STATUS_MANIFEST_SCHEMA_URL,
  ARK_STATUS_MANIFEST_SCHEMA_VERSION,
  STATUS_COMPASS_FACTS_SOURCES,
  STATUS_COMPASS_MODES,
  STATUS_COMPASS_REASON_CODES,
  buildStatusManifest,
  classifyStatusWritePath,
  defaultHonestLabel,
  evaluateStatusBinding,
  normalizeStatusImprovementCompass,
  projectStatusImprovementCompass,
  resolveStatusNextAction,
  statusCompassResidualIsSubsetOfDoctor,
  unavailableStatusImprovementCompass,
  type StatusActivationSlice,
  type StatusCheckVerdict,
  type StatusCompassFactsSource,
  type StatusCompassMode,
  type StatusCompassReasonCode,
  type StatusImprovementCompassSlice,
  type StatusLastCheckSlice,
  type StatusManifest,
  type StatusManifestFacts,
  type StatusNextAction,
  type StatusProjectIdentitySlice,
  type StatusRulesSlice,
  type StatusWritePathClass,
} from './domain/statusManifest';

export {
  ARK_IMPROVEMENT_COMPASS_SCHEMA_VERSION,
  IMPROVEMENT_COMPASS_OUT_OF_SCOPE_LENSES,
  IMPROVEMENT_COMPASS_TOP_RESIDUAL_CAP,
  IMPROVEMENT_LENS_IDS,
  buildImprovementCompass,
  formatImprovementCompassDoctorLines,
  formatImprovementCompassResidualLabels,
  primaryImprovementCompassNextAction,
  type ImprovementCompass,
  type ImprovementCompassEvidence,
  type ImprovementCompassFacts,
  type ImprovementCompassNextAction,
  type ImprovementCompassSmellFact,
  type ImprovementCompassViolationFact,
  type ImprovementLens,
  type ImprovementLensId,
  type ImprovementLensStatus,
} from './domain/improvementCompass';

export {
  AGENT_PROJECTION_BEGIN_MARKER,
  AGENT_PROJECTION_END_MARKER,
  AGENT_PROJECTION_ENFORCEMENT_SURFACES,
  AGENT_PROJECTION_NON_ENFORCEMENT_LABEL,
  ARK_AGENT_PROJECTION_SCHEMA_VERSION,
  DEFAULT_AGENT_PROJECTION_RULE_IDS,
  agentProjectionContentIdentity,
  buildAgentProjectionBeginMarker,
  buildAgentProjectionBlock,
  buildAgentProjectionBody,
  buildAgentProjectionMeta,
  extractAgentProjectionBlock,
  formatAgentProjectionCatalogShortList,
  formatAgentProjectionLayers,
  mergeAgentProjectionDocument,
  parseAgentProjectionStamp,
  projectionHasNonEnforcementLabel,
  projectionMatchesPackageVersion,
  type AgentProjectionCatalogEntry,
  type AgentProjectionFacts,
  type AgentProjectionLayerSummary,
  type AgentProjectionMergeAction,
  type AgentProjectionMergeResult,
  type AgentProjectionMeta,
  type AgentProjectionProfile,
} from './domain/agentProjection';

export {
  AGENT_SKILL_ENTRY_FILENAME,
  AGENT_SKILLS_PACKAGE_RELATIVE_ROOT,
  ARK_AGENT_SKILLS_PACKAGE_SCHEMA_VERSION,
  ARK_SKILL_NAMES,
  ARK_SKILL_NAME_COUNT,
  ARK_SKILL_DESCRIPTION_VERSION_PATTERN,
  FLAT_SKILL_TEMPLATES_RELATIVE_ROOT,
  agentSkillEntryRelativePath,
  agentSkillPackageFileRelativePath,
  flatSkillTemplateFileRelativePath,
  isArkSkillName,
  isValidAgentSkillName,
  normalizeSkillContent,
  parseSkillDescriptionVersion,
  parseSkillDocument,
  stampSkillDescription,
  stripSkillDescriptionVersion,
  skillDescriptionVersionPrefix,
  validateAgentSkillDocument,
  validateAgentSkillsPackage,
  type AgentSkillPackageEntry,
  type AgentSkillValidationIssue,
  type ArkSkillName,
  type ParseSkillDocumentResult,
  type ParsedSkillFrontmatter,
  type ValidateAgentSkillDocumentInput,
  type ValidateAgentSkillsPackageResult,
} from './domain/agentSkillsPackage';
